cache: yarn
language: node_js
node_js:
  - "node"
  - "7"
install:
 - yarn
 - yarn global add codecov
script:
 - yarn test
 - codecov
addons:
  apt:
    packages:
    - libzmq3-dbg
    - libzmq3-dev
    - libzmq3
